import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import FooterWrapper from "./components/FooterWrapper";
import { AuthProvider } from './components/auth/AuthProvider';
import { AuthModalProvider } from './components/auth/AuthModalContext';
import AuthModal from './components/auth/AuthModal';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthModalProvider>
          <AuthProvider>
            <AuthModal />
            <Header />
            {children}
            <FooterWrapper />
          </AuthProvider>
        </AuthModalProvider>
      </body>
    </html>
  );
}
